// Announcement post templates (at least 10)
export const announcementPosts = [
  `📢 Introducing {coinName} ({ticker}) on PulseChain! {theme} #PulseChain #DeFi`,
  `🚀 {coinName} ({ticker}) launches! Join the revolution. {theme} #PulseChain #Crypto`,
  `🎉 {coinName} ({ticker}) is live! Discover the future of DeFi. {theme} #PulseChain`,
  `🌟 {coinName} ({ticker}) is here to change the game! {theme} #PulseChain #Innovation`,
  `🔥 Don't miss out on {coinName} ({ticker})! {theme} #PulseChain #Launch`,
  `💎 {coinName} ({ticker}): Your next big investment! {theme} #PulseChain #Opportunity`,
  `📈 {coinName} ({ticker}) is now trading! {theme} #PulseChain #CryptoNews`,
  `🎊 Celebrate the launch of {coinName} ({ticker})! {theme} #PulseChain #Community`,
  `🚀 Ready for takeoff? {coinName} ({ticker}) is live! {theme} #PulseChain #ToTheMoon`,
  `🌈 The future is bright with {coinName} ({ticker})! {theme} #PulseChain #Future`,
  `🛡️ Secure your spot in {coinName} ({ticker}) early! {theme} #PulseChain #EarlyAdopter`,
  `💥 {coinName} ({ticker}) is making waves! {theme} #PulseChain #Trending`,
  `🧑‍🚀 Join the {coinName} ({ticker}) mission! {theme} #PulseChain #Mission`,
  `🎯 Target set: {coinName} ({ticker}) to the moon! {theme} #PulseChain #MoonMission`,
  `📰 Breaking: {coinName} ({ticker}) launches on PulseChain! {theme} #PulseChain #BreakingNews`,
  `🏆 {coinName} ({ticker}) - Be part of the winning team! {theme} #PulseChain #Winners`,
  `🧬 {coinName} ({ticker}) - The DNA of next-gen DeFi! {theme} #PulseChain #NextGen`,
  `🌍 {coinName} ({ticker}) is going global! {theme} #PulseChain #Global`,
  `🎤 AMA soon: Learn about {coinName} ({ticker})! {theme} #PulseChain #AMA`,
  `🕒 Countdown to {coinName} ({ticker}) launch! {theme} #PulseChain #Countdown`,
  `💡 Discover the vision behind {coinName} ({ticker})! {theme} #PulseChain #Vision`,
  `🎬 Watch {coinName} ({ticker}) make history! {theme} #PulseChain #History`,
  `🧩 {coinName} ({ticker}) - The missing piece in DeFi! {theme} #PulseChain #Puzzle`,
  `🎨 {coinName} ({ticker}) - Where art meets blockchain! {theme} #PulseChain #Art`,
  `🦄 {coinName} ({ticker}) - Unleash the magic! {theme} #PulseChain #Magic`,
  `🛸 {coinName} ({ticker}) - Out of this world! {theme} #PulseChain #UFO`,
  `🎲 Take a chance on {coinName} ({ticker})! {theme} #PulseChain #Luck`,
  `🧠 Smart money is on {coinName} ({ticker})! {theme} #PulseChain #SmartMoney`,
  `🎁 Surprise drops coming for {coinName} ({ticker}) holders! {theme} #PulseChain #Airdrop`,
  `🏅 {coinName} ({ticker}) - Join the elite! {theme} #PulseChain #Elite`
];
