import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Shuffle, Copy, Save, Sparkles } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

interface CoinIdea {
  name: string;
  ticker: string;
  theme: string;
  logoIdea: string;
}

const IdeaGenerator = ({ coinIdea, setCoinIdea }: { coinIdea: CoinIdea | null, setCoinIdea: (idea: CoinIdea) => void }) => {
  const [theme, setTheme] = useState('');
  const [generatedIdea, setGeneratedIdea] = useState<CoinIdea | null>(coinIdea);
  const [isGenerating, setIsGenerating] = useState(false);
  const [showConfetti, setShowConfetti] = useState(false);
  const { toast } = useToast();

  const themeVariations = {
    animal: ['frog', 'dog', 'cat', 'hamster', 'monkey', 'shark', 'whale', 'dolphin', 'penguin', 'tiger'],
    space: ['galaxy', 'mars', 'moon', 'stars', 'rocket', 'astronaut', 'alien', 'comet', 'nebula', 'planet'],
    food: ['pizza', 'burger', 'taco', 'donut', 'cake', 'cookie', 'banana', 'apple', 'coffee', 'beer'],
    object: ['diamond', 'crown', 'sword', 'shield', 'key', 'lamp', 'chair', 'phone', 'car', 'house'],
    emotion: ['happy', 'angry', 'sleepy', 'excited', 'confused', 'surprised', 'cool', 'silly', 'brave', 'chill']
  };

  const prefixes = ['Pulse', 'Chain', 'Mega', 'Super', 'Ultra', 'Crypto', 'Degen', 'Moon', 'Rocket', 'Turbo'];
  const suffixes = ['Coin', 'Token', 'Pulse', 'Chain', 'X', 'Finance', 'Swap', 'Protocol', 'DAO', 'Network'];

  const generateIdea = (inputTheme?: string) => {
    setIsGenerating(true);
    
    setTimeout(() => {
      let selectedTheme = inputTheme || theme;
      
      // If no theme provided, pick random
      if (!selectedTheme) {
        const categories = Object.values(themeVariations).flat();
        selectedTheme = categories[Math.floor(Math.random() * categories.length)];
      }
      
      const prefix = prefixes[Math.floor(Math.random() * prefixes.length)];
      const suffix = suffixes[Math.floor(Math.random() * suffixes.length)];
      
      const capitalizedTheme = selectedTheme.charAt(0).toUpperCase() + selectedTheme.slice(1);
      const coinName = Math.random() > 0.5 ? `${prefix}${capitalizedTheme}` : `${capitalizedTheme}${suffix}`;
      const ticker = `$${coinName.toUpperCase().substring(0, 6)}`;
      
      const logoIdeas = [
        `A cartoon ${selectedTheme} wearing a PulseChain crown`,
        `A futuristic ${selectedTheme} with laser eyes and purple aura`,
        `A ${selectedTheme} surfing on blockchain waves`,
        `A minimalist ${selectedTheme} icon with pulse heartbeat lines`,
        `A ${selectedTheme} astronaut floating in purple space`,
        `A geometric ${selectedTheme} with gradient purple-to-orange colors`
      ];
      
      const newIdea: CoinIdea = {
        name: coinName,
        ticker: ticker,
        theme: `A ${selectedTheme}-themed meme coin bringing fun and community to PulseChain.`,
        logoIdea: logoIdeas[Math.floor(Math.random() * logoIdeas.length)]
      };
      
      setGeneratedIdea(newIdea);
      setIsGenerating(false);
      setShowConfetti(true);
      setCoinIdea(newIdea); // sync with parent
      // Save to localStorage
      localStorage.setItem('lastGeneratedIdea', JSON.stringify(newIdea));
      
      setTimeout(() => setShowConfetti(false), 3000);
      
      toast({
        title: "Meme Coin Idea Generated! 🎉",
        description: `Generated ${newIdea.name} (${newIdea.ticker})`,
      });
    }, 1500);
  };

  const copyAllDetails = () => {
    if (!generatedIdea) return;
    
    const details = `🚀 MEME COIN IDEA 🚀

💎 Name: ${generatedIdea.name}
🎯 Ticker: ${generatedIdea.ticker}
📝 Theme: ${generatedIdea.theme}
🎨 Logo Idea: ${generatedIdea.logoIdea}

Generated by MemePulse - Your PulseChain Meme Coin Generator`;

    navigator.clipboard.writeText(details);
    toast({
      title: "Copied to Clipboard! 📋",
      description: "All coin details have been copied.",
    });
  };

  const saveIdea = () => {
    if (!generatedIdea) return;
    
    const savedIdeas = JSON.parse(localStorage.getItem('savedIdeas') || '[]');
    savedIdeas.push({ ...generatedIdea, timestamp: new Date().toISOString() });
    localStorage.setItem('savedIdeas', JSON.stringify(savedIdeas));
    
    toast({
      title: "Idea Saved! 💾",
      description: "Your meme coin idea has been saved locally.",
    });
  };

  return (
    <section id="generator" className="py-20 bg-gradient-to-br from-gray-900 to-black relative">
      {showConfetti && (
        <div className="fixed inset-0 pointer-events-none z-50">
          {[...Array(50)].map((_, i) => (
            <div
              key={i}
              className="absolute w-2 h-2 bg-pulse-orange rounded-full animate-bounce"
              style={{
                left: `${Math.random() * 100}%`,
                animationDelay: `${Math.random() * 2}s`,
                animationDuration: `${1 + Math.random()}s`
              }}
            />
          ))}
        </div>
      )}
      
      <div className="container mx-auto px-4">
        <div className="text-center mb-12">
          <h2 className="font-orbitron text-4xl md:text-6xl font-bold text-white mb-4">
            💡 Meme Coin Idea Generator
          </h2>
          <p className="text-xl text-gray-400 max-w-2xl mx-auto">
            Enter a theme or keyword and let AI generate your next viral PulseChain meme coin idea!
          </p>
        </div>
        
        <div className="max-w-4xl mx-auto">
          <Card className="bg-card/80 backdrop-blur-md border-purple-500/20 shadow-2xl">
            <CardHeader>
              <CardTitle className="text-2xl font-orbitron text-center">Generate Your Meme Coin</CardTitle>
            </CardHeader>
            <CardContent className="space-y-6">
              <div className="flex flex-col md:flex-row gap-4">
                <Input
                  placeholder="Enter a theme/keyword (e.g., frog, toaster, galaxy)"
                  value={theme}
                  onChange={(e) => setTheme(e.target.value)}
                  className="flex-1 bg-black/50 border-gray-600 text-white placeholder-gray-400"
                />
                <div className="flex gap-2">
                  <Button
                    onClick={() => generateIdea()}
                    disabled={isGenerating}
                    className="bg-gradient-to-r from-pulse-purple to-pulse-orange hover:from-pulse-orange hover:to-pulse-purple transition-all duration-300 px-8"
                  >
                    {isGenerating ? (
                      <div className="flex items-center gap-2">
                        <div className="w-4 h-4 border-2 border-white border-t-transparent rounded-full animate-spin" />
                        Generating...
                      </div>
                    ) : (
                      <div className="flex items-center gap-2">
                        <Sparkles className="w-4 h-4" />
                        Generate Idea!
                      </div>
                    )}
                  </Button>
                  <Button
                    onClick={() => generateIdea('')}
                    variant="outline"
                    className="border-gray-600 hover:bg-gray-800"
                  >
                    <Shuffle className="w-4 h-4" />
                  </Button>
                </div>
              </div>
              
              {generatedIdea && (
                <div className="mt-8 p-6 bg-gradient-to-br from-purple-900/20 to-orange-900/20 rounded-lg border border-purple-500/30">
                  <div className="grid md:grid-cols-2 gap-6">
                    <div className="space-y-4">
                      <div>
                        <h3 className="font-orbitron text-lg font-bold text-pulse-orange mb-2">
                          🪙 Coin Name
                        </h3>
                        <p className="text-2xl font-bold text-white">{generatedIdea.name}</p>
                      </div>
                      
                      <div>
                        <h3 className="font-orbitron text-lg font-bold text-pulse-orange mb-2">
                          🎯 Ticker Symbol
                        </h3>
                        <p className="text-2xl font-bold text-green-400">{generatedIdea.ticker}</p>
                      </div>
                    </div>
                    
                    <div className="space-y-4">
                      <div>
                        <h3 className="font-orbitron text-lg font-bold text-pulse-orange mb-2">
                          📝 Theme Summary
                        </h3>
                        <p className="text-gray-300">{generatedIdea.theme}</p>
                      </div>
                      
                      <div>
                        <h3 className="font-orbitron text-lg font-bold text-pulse-orange mb-2">
                          🎨 Logo Idea
                        </h3>
                        <p className="text-gray-300">{generatedIdea.logoIdea}</p>
                      </div>
                    </div>
                  </div>
                  
                  <div className="flex flex-wrap gap-4 mt-6 pt-4 border-t border-gray-600">
                    <Button
                      onClick={copyAllDetails}
                      variant="outline"
                      className="flex items-center gap-2 border-gray-600 hover:bg-gray-800"
                    >
                      <Copy className="w-4 h-4" />
                      Copy All Details
                    </Button>
                    <Button
                      onClick={saveIdea}
                      variant="outline"
                      className="flex items-center gap-2 border-gray-600 hover:bg-gray-800"
                    >
                      <Save className="w-4 h-4" />
                      Save Idea
                    </Button>
                  </div>
                </div>
              )}
            </CardContent>
          </Card>
        </div>
      </div>
    </section>
  );
};

export default IdeaGenerator;
